/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AADS_Contact_Services_Gradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
